version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: omar
      POSTGRES_PASSWORD: omar
      POSTGRES_DB: edulib
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://your_username:your_password@db:5432/your_database_name
